services:
  - type: web
    name: david-inspiration
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PLAYHT_API_KEY
        sync: false
      - key: PLAYHT_USER_ID
        sync: false
      - key: PLAYHT_VOICE_ID
        sync: false